apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-test-coll-a2169c2dcaeb48428f2538653624a002-depl
  labels:
    app: new-test-coll-a2169c2dcaeb48428f2538653624a002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-test-coll-a2169c2dcaeb48428f2538653624a002
  template:
    metadata:
      labels:
        app: new-test-coll-a2169c2dcaeb48428f2538653624a002
    spec:
      containers:
        - name: new-test-coll-a2169c2dcaeb48428f2538653624a002
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:new-test-coll-a2169c2dcaeb48428f2538653624a002
          imagePullPolicy: Always
          ports:
            - containerPort: 9014